import express from "express";
import cors from "cors";
import authRoutes from "./routes/auth.js";
import dotenv from "dotenv";
import passport from "passport";
import fetchDonationsRoutes from "./routes/fetch-donations.js";
import fetchStaffDonationsRoutes from "./routes/staff-fetch-donations.js";
import addDonationRoutes from "./routes/add-donation.js";
import donationOptionsRoutes from "./routes/donation-options.js";
import fetchUserInfoRoutes from "./routes/fetch-userinfo.js";
import updateUserInfoRoutes from "./routes/update-userinfo.js";
import fetchDonation from "./routes/fetch-donation.js";
import updateDonation from "./routes/update-donation.js";
import donationImageRouter from "./routes/donation-image.js";
import deleteOwnUser from "./routes/delete-own-user.js";
import fetchDonationCount from "./routes/fetch-donationcount.js";
import fetchNotifications from "./routes/fetch-notifications.js";
import updateNotification from "./routes/update-notification.js";
import fetchUsers from "./routes/fetch-users.js";
import updateUsers from "./routes/update-users.js";
import createUsers from "./routes/create-users.js";
import deleteUsers from "./routes/delete-users.js";
import genImageDescription from "./routes/gen-image-description.js";
import genSelectOptions from "./routes/gen-select-options.js";

dotenv.config({ path: "../.env" });
const app = express();
app.use(cors());
app.use(express.json({ limit: "10mb" }));
app.use(express.urlencoded({ limit: "10mb", extended: true }));
app.use(express.json());
app.use(passport.initialize());
app.use("/api/auth", authRoutes);
app.use("/api/fetch-donations", fetchDonationsRoutes);
app.use("/api/staff-donations", fetchStaffDonationsRoutes);
app.use("/api/add-donation", addDonationRoutes);
app.use("/api/donation-options", donationOptionsRoutes);
app.use("/api/fetch-userinfo", fetchUserInfoRoutes);
app.use("/api/update-userinfo", updateUserInfoRoutes);
app.use("/api/fetch-donation", fetchDonation);
app.use("/api/update-donation", updateDonation);
app.use("/api/donation-image", donationImageRouter);
app.use("/api/delete-own-user", deleteOwnUser);
app.use("/api/fetch-donationcount", fetchDonationCount);
app.use("/api/fetch-notifications", fetchNotifications);
app.use("/api/update-notification", updateNotification);
app.use("/api/fetch-users", fetchUsers);
app.use("/api/update-users", updateUsers);
app.use("/api/create-users", createUsers);
app.use("/api/delete-users", deleteUsers);
app.use("/api/gen-image-description", genImageDescription);
app.use("/api/gen-select-options", genSelectOptions);

app.listen(3000, () => {
  console.log("Backend running on http://localhost:3000");
});
